export interface GlossaryTerm {
  term: string;
  acronym?: string;
  category: 'claims' | 'coding' | 'payer' | 'tech' | 'metrics';
  categoryLabel: string;
  definition: string;
  clinicalImpact: string;
  example: string;
  toolHref?: string;
  toolLabel?: string;
}

export const GLOSSARY_TERMS: GlossaryTerm[] = [
  {
    term: '837P (EDI 837 Professional)',
    acronym: '837P',
    category: 'tech',
    categoryLabel: 'Technology & EDI',
    definition: 'The standard HIPAA-mandated electronic data interchange (EDI) format used by healthcare providers, clinics, and billing companies to transmit professional outpatient claims to commercial health plans, Medicare, and Medicaid.',
    clinicalImpact: 'Formatting errors in loop 2000A (billing provider), loop 2010BA (subscriber), or loop 2400 (service lines) trigger instant clearinghouse rejections before reaching payer adjudication.',
    example: 'A multi-provider family clinic transmits an 837P batch containing 120 claims daily at 5:00 PM through their clearinghouse.',
    toolHref: '/tools/era-835-decoder',
    toolLabel: 'EDI & ERA Tool',
  },
  {
    term: '835 ERA (Electronic Remittance Advice)',
    acronym: '835 ERA',
    category: 'tech',
    categoryLabel: 'Technology & EDI',
    definition: 'An automated electronic transaction sent by insurance payers to providers detailing claim adjudication, payment amounts, contractual write-offs, and patient liability.',
    clinicalImpact: 'Eliminates manual paper EOB entry, automatically reconciling bank deposits via EFT while capturing CARC and RARC adjustment reason codes.',
    example: 'UnitedHealthcare returns an 835 remittance file showing $154.20 allowed for CPT 99214, with $25.00 assigned to Group PR (patient copay).',
    toolHref: '/tools/era-835-decoder',
    toolLabel: 'Decode 835 Remittances',
  },
  {
    term: 'CARC (Claim Adjustment Reason Code)',
    acronym: 'CARC',
    category: 'claims',
    categoryLabel: 'Billing & Claims',
    definition: 'National standard numeric codes maintained by X12 that communicate why a claim or service line was paid at a different amount than originally billed.',
    clinicalImpact: 'Essential for denial analysis and automated workflow routing. Specific codes indicate whether a denial requires medical records (CARC 50), pre-auth (CARC 197), or unbundling corrections (CARC 97).',
    example: 'A claim for same-day evaluation and injection returns CARC 97: "The benefit for this service is included in the payment for another service."',
    toolHref: '/tools/denial-code-lookup',
    toolLabel: 'Lookup 1,283+ CARC Codes',
  },
  {
    term: 'RARC (Remittance Advice Remark Code)',
    acronym: 'RARC',
    category: 'claims',
    categoryLabel: 'Billing & Claims',
    definition: 'Standard alphanumeric remark codes used in conjunction with CARCs to provide granular, line-level explanations for claim adjustments and payment policies.',
    clinicalImpact: 'Clarifies vague CARC denials, pinpointing the missing documentation, secondary insurer coordination requirements, or specific policy exclusions.',
    example: 'A denial marked CARC 16 is paired with RARC N257: "Missing/incomplete/invalid documentation," instructing billers to submit the physician operative report.',
    toolHref: '/tools/denial-code-lookup',
    toolLabel: 'Lookup Remark Codes',
  },
  {
    term: 'NCCI (National Correct Coding Initiative)',
    acronym: 'NCCI',
    category: 'coding',
    categoryLabel: 'Coding & Modifiers',
    definition: 'CMS-developed coding methodologies designed to promote national correct coding practices and control improper coding leading to inappropriate payment in Part B claims.',
    clinicalImpact: 'Enforces automated Procedure-to-Procedure (PTP) edits and Medically Unlikely Edits (MUEs), penalizing practices for routine unbundling.',
    example: 'Billing CPT 99214 with 99213 for the same patient on the same day triggers an NCCI bundling edit with a modifier indicator of 0 (unbundling prohibited).',
    toolHref: '/tools/ncci-claim-scrubber',
    toolLabel: 'CMS NCCI Claim Scrubber',
  },
  {
    term: 'PTP Edits (Procedure-to-Procedure)',
    acronym: 'PTP',
    category: 'coding',
    categoryLabel: 'Coding & Modifiers',
    definition: 'Specific pairs of HCPCS/CPT codes that should not normally be billed together for the same patient on the same date of service because one is deemed integral to the other.',
    clinicalImpact: 'PTP Column 1 / Column 2 tables determine which code is eligible for payment and whether a designated modifier (e.g. Mod 59, XE) is permitted to unbundle them.',
    example: 'Trigger point injection (20552) and arthrocentesis (20610) performed on separate anatomical sites require Modifier 59 or XS to bypass PTP bundling.',
    toolHref: '/tools/ncci-claim-scrubber',
    toolLabel: 'Validate PTP Modifier Indicators',
  },
  {
    term: 'MUE (Medically Unlikely Edit)',
    acronym: 'MUE',
    category: 'coding',
    categoryLabel: 'Coding & Modifiers',
    definition: 'The maximum units of service that a provider would report under most circumstances for a single beneficiary on a single date of service for a specific CPT or HCPCS code.',
    clinicalImpact: 'Excess units billed above the MUE value are denied automatically under CARC 151. Units cannot be appealed unless anatomically distinct and supported by an operative note.',
    example: 'CPT 66984 (cataract surgery) has an MUE of 2 (one per eye maximum), while CPT 99214 has an MUE of 1 per provider per day.',
    toolHref: '/tools/ncci-claim-scrubber',
    toolLabel: 'Scrub Claims for MUE Limits',
  },
  {
    term: 'Modifier 25',
    category: 'coding',
    categoryLabel: 'Coding & Modifiers',
    definition: 'A billing modifier appended to an Evaluation and Management (E/M) service indicating that on the day of a minor surgical procedure, the patient\'s condition required a significant, separately identifiable E/M.',
    clinicalImpact: 'Heavily audited by commercial payers and Medicare MACs. Prepayment review and prepayment denials are common without clear clinical documentation demonstrating care above routine pre-op/post-op work.',
    example: 'A dermatologist performs a scheduled biopsy (11102) and separately evaluates a new, unrelated suspicious rash elsewhere on the body, appending Modifier 25 to 99213.',
    toolHref: '/tools/ncci-claim-scrubber',
    toolLabel: 'Modifier 25 Documentation Audit',
  },
  {
    term: 'Modifier 59',
    category: 'coding',
    categoryLabel: 'Coding & Modifiers',
    definition: 'The "unbundling modifier" used to identify procedures or services that are not normally reported together, but are clinically distinct and independent under the specific circumstances of the encounter.',
    clinicalImpact: 'Often called the modifier of last resort. Misuse triggers fraud and abuse audits; CMS encourages the use of more specific X{EPSU} modifiers whenever applicable.',
    example: 'A physician excises two distinct lesions located on different anatomical limbs (e.g., right arm and left thigh) during the same surgical session.',
    toolHref: '/tools/ncci-claim-scrubber',
    toolLabel: 'Check Modifier 59 Rules',
  },
  {
    term: 'X{EPSU} Modifiers',
    category: 'coding',
    categoryLabel: 'Coding & Modifiers',
    definition: 'Four specific HCPCS modifiers established by CMS to provide greater specificity than Modifier 59: XE (Separate Encounter), XS (Separate Structure), XP (Separate Practitioner), and XU (Unusual Non-Overlapping Service).',
    clinicalImpact: 'Bypasses NCCI edits with lower audit scrutiny because it documents the exact clinical rationale for unbundling.',
    example: 'Using Modifier XS instead of Modifier 59 on a bilateral joint injection clearly communicates that the second procedure was performed on a separate joint structure.',
    toolHref: '/tools/ncci-claim-scrubber',
    toolLabel: 'Validate X{EPSU} Indicators',
  },
  {
    term: 'ABN (Advance Beneficiary Notice)',
    acronym: 'ABN',
    category: 'payer',
    categoryLabel: 'Payer & Compliance',
    definition: 'A standardized written notice (Form CMS-R-131) issued to a Fee-for-Service Medicare patient before providing an item or service that Medicare is expected to deny as not medically necessary.',
    clinicalImpact: 'Without a properly executed ABN signed before service delivery, the provider cannot legally collect payment from the patient and must write off the entire balance (Mod GA vs GZ).',
    example: 'A physician ordering high-frequency vitamin D testing that falls outside Medicare LCD frequency criteria obtains a signed ABN from the patient.',
    toolHref: '/tools/eligibility-checklist',
    toolLabel: 'Review Eligibility Checklist',
  },
  {
    term: 'LCD & NCD (Coverage Determinations)',
    acronym: 'LCD / NCD',
    category: 'payer',
    categoryLabel: 'Payer & Compliance',
    definition: 'National Coverage Determinations (NCDs) and Local Coverage Determinations (LCDs) are statutory Medicare guidelines establishing whether a medical service is considered reasonable and medically necessary.',
    clinicalImpact: 'Listing a non-covered ICD-10 diagnosis code that is absent from the applicable LCD table triggers an immediate, unappealable CARC 50 medical necessity denial.',
    example: 'Billing hyperbaric oxygen therapy under Medicare Part B requires strict adherence to LCD-specified chronic wound classifications.',
    toolHref: '/tools/appeal-letter-generator',
    toolLabel: 'Generate LCD Appeal Letters',
  },
  {
    term: 'MAC (Medicare Administrative Contractor)',
    acronym: 'MAC',
    category: 'payer',
    categoryLabel: 'Payer & Compliance',
    definition: 'A private health care insurer that has been awarded a geographic jurisdiction by CMS to process Medicare Part A and Part B medical claims and durable medical equipment (DME) claims.',
    clinicalImpact: 'Each MAC (e.g., Novitas, First Coast, Noridian, Palmetto, WPS) maintains distinct Local Coverage Determinations (LCDs) and medical audit priorities.',
    example: 'A practice in Florida files Medicare Part B claims to First Coast Service Options (Jurisdiction N), adhering to FCSO local coding guidelines.',
    toolHref: '/tools/timely-filing-matrix',
    toolLabel: 'Check Multi-Payer Rules',
  },
  {
    term: 'COB (Coordination of Benefits)',
    acronym: 'COB',
    category: 'claims',
    categoryLabel: 'Billing & Claims',
    definition: 'The legal process of determining which health plan has primary payment responsibility when a patient is covered by more than one health insurance policy.',
    clinicalImpact: 'Failure to confirm the correct COB order leads to CARC 109 and CARC 22 denials, followed by retrospective payer clawbacks months after payment.',
    example: 'When a patient has commercial group coverage through work and Medicare, Medicare is secondary if the employer has 20 or more employees.',
    toolHref: '/tools/era-835-decoder',
    toolLabel: 'Decode COB Payments & Groups',
  },
  {
    term: 'Clean Claim Rate (CCR)',
    acronym: 'CCR',
    category: 'metrics',
    categoryLabel: 'Financial Metrics',
    definition: 'The percentage of medical claims submitted to clearinghouses and payers that are successfully processed and paid on their first submission without rejections or human touch.',
    clinicalImpact: 'Industry average hovers between 75%–85%. High-performing practices maintained by Aethera achieve 98%+, dramatically shortening revenue cycle turnaround.',
    example: 'A clinic submitting 1,000 claims per month with 980 accepted and paid without denial maintains a 98.0% Clean Claim Rate.',
    toolHref: '/tools/clean-claim-scorecard',
    toolLabel: 'Calculate Your Clean Claim Score',
  },
  {
    term: 'Days in A/R (DSO)',
    acronym: 'AR Days',
    category: 'metrics',
    categoryLabel: 'Financial Metrics',
    definition: 'A benchmark financial metric measuring the average number of days it takes for a medical practice to receive payment on claims after the date of clinical service.',
    clinicalImpact: 'DSO > 50 days signals severe claim submission bottlenecks, unworked denials, or ineffective patient collection follow-up, locking up liquid capital.',
    example: 'A practice with $300,000 in outstanding accounts receivable and $10,000 daily revenue has 30 Days in A/R ($300,000 ÷ $10,000).',
    toolHref: '/tools/ar-cost-calculator',
    toolLabel: 'Calculate A/R Carrying Cost',
  },
  {
    term: 'Prior Authorization (PA)',
    acronym: 'PA',
    category: 'claims',
    categoryLabel: 'Billing & Claims',
    definition: 'A requirement by health insurance companies that providers obtain advance approval before delivering a prescribed procedure, medication, or imaging study.',
    clinicalImpact: 'Missing, expired, or mismatched prior authorization numbers generate CARC 197 hard denials, which are notoriously difficult to overturn retroactively.',
    example: 'An orthopedic surgeon submits an advance clinical package to Aetna to authorize a total knee arthroplasty (CPT 27447) prior to operating.',
    toolHref: '/tools/appeal-letter-generator',
    toolLabel: 'Draft Prior Auth Denial Appeal',
  },
  {
    term: 'Timely Filing Limit',
    category: 'payer',
    categoryLabel: 'Payer & Compliance',
    definition: 'The strict contractual deadline set by health plans within which a clean claim must be received following the date of clinical service to be eligible for reimbursement.',
    clinicalImpact: 'Missing the filing window results in CARC 29 denials. These amounts cannot be billed to the patient under in-network provider contracts and must be 100% written off.',
    example: 'Medicare enforces a 365-day timely filing window, whereas commercial health plans like UnitedHealthcare or Aetna often enforce 90-day limits.',
    toolHref: '/tools/timely-filing-matrix',
    toolLabel: 'Browse 50-State Filing Matrix',
  },
  {
    term: 'Global Surgical Period',
    category: 'coding',
    categoryLabel: 'Coding & Modifiers',
    definition: 'A designated post-operative timeframe (0, 10, or 90 days) during which all routine postoperative E/M care related to the surgical procedure is bundled into the surgical fee.',
    clinicalImpact: 'E/M visits during the global window are denied under CARC 97 unless related to an unrelated condition (Modifier 24) or a staged/unplanned return to OR (Modifier 58/78/79).',
    example: 'A 90-day global surgical period follows major spine surgery; routine suture removal on day 14 cannot be billed as a separate office visit.',
    toolHref: '/tools/ncci-claim-scrubber',
    toolLabel: 'Audit Global Surgery Modifiers',
  },
  {
    term: '8-Minute Rule',
    category: 'coding',
    categoryLabel: 'Coding & Modifiers',
    definition: 'Medicare\'s statutory calculation method for billing timed physical medicine and rehabilitation service codes (e.g., CPT 97110, 97140, 97530).',
    clinicalImpact: 'Providers must deliver at least 8 minutes of direct, one-on-one therapy to bill 1 unit. Total treatment time across all timed codes dictates the allowable cumulative unit count.',
    example: 'A physical therapist providing 25 minutes of therapeutic exercise and 15 minutes of manual therapy (40 total mins) is permitted to bill exactly 3 total units.',
    toolHref: '/medical-billing/physical-therapy',
    toolLabel: 'Physical Therapy Playbook',
  },
  {
    term: 'JW / JZ Modifiers',
    category: 'coding',
    categoryLabel: 'Coding & Modifiers',
    definition: 'Mandatory CMS billing modifiers used with single-dose vial drugs. Modifier JW reports exact amounts discarded, while Modifier JZ attests that zero waste occurred.',
    clinicalImpact: 'Omitting JZ or JW on Part B buy-and-bill drugs results in automated claim rejections and potential OIG compliance audits for unverified drug wastage.',
    example: 'Administering 80 units of a 100-unit single-use Botox vial requires billing 80 units without modifier and 20 units with Modifier JW on a second line.',
    toolHref: '/medical-billing/neurology',
    toolLabel: 'Neurology & Buy-and-Bill Guide',
  },
  {
    term: 'RVU (Relative Value Unit)',
    acronym: 'RVU',
    category: 'metrics',
    categoryLabel: 'Financial Metrics',
    definition: 'The standardized metric CMS assigns to every CPT code to evaluate the relative resources required to provide the service: Work (wRVU), Practice Expense (peRVU), and Malpractice (mpRVU).',
    clinicalImpact: 'Forms the foundational basis for physician compensation formulas, Medicare fee schedules, and commercial contract negotiations.',
    example: 'An established patient visit CPT 99214 carries approximately 1.92 work RVUs, reflecting moderate medical decision-making complexity.',
    toolHref: '/tools/rvu-calculator',
    toolLabel: 'Calculate Total RVUs & Rates',
  },
  {
    term: 'GPCI (Geographic Practice Cost Index)',
    acronym: 'GPCI',
    category: 'metrics',
    categoryLabel: 'Financial Metrics',
    definition: 'Geographic adjustments applied to each RVU component to account for regional differences in physician salaries, office rents, staff wages, and malpractice insurance premiums.',
    clinicalImpact: 'Urban practices in high-cost regions (e.g., Manhattan, San Francisco) receive positive payment adjustments compared to rural fee schedule baselines.',
    example: 'Manhattan malpractice GPCI is approximately 1.642, compensating physicians for elevated regional liability insurance expenses.',
    toolHref: '/tools/rvu-calculator',
    toolLabel: 'Lookup Locality GPCI Values',
  },
  {
    term: 'Conversion Factor (CF)',
    acronym: 'CF',
    category: 'metrics',
    categoryLabel: 'Financial Metrics',
    definition: 'The fixed dollar multiplier established annually by CMS statute that converts the geographically adjusted total RVUs of a service into the final Medicare allowable payment.',
    clinicalImpact: 'Congressional updates and CMS fee cuts directly alter this single factor, impacting top-line practice revenue across all Medicare Part B billings.',
    example: 'For CY2026, the Medicare Physician Fee Schedule conversion factor is established at $33.40 for non-qualifying APM participants.',
    toolHref: '/tools/fee-schedule-benchmarker',
    toolLabel: 'Benchmark 2026 CMS Rates',
  },
  {
    term: 'EOB (Explanation of Benefits)',
    acronym: 'EOB',
    category: 'claims',
    categoryLabel: 'Billing & Claims',
    definition: 'A document provided by insurance carriers to patients summarizing medical treatments covered, payment made to the doctor, contractual reductions, and patient copay/coinsurance responsibility.',
    clinicalImpact: 'Not a bill, but vital for transparent patient billing. Transparent EOBs reduce patient billing confusion and prevent angry billing disputes.',
    example: 'A patient reviews an EOB showing a $250 clinic charge, a $105 insurance discount, an $115 insurer payment, and a $30 patient copay balance.',
    toolHref: '/services/patient-collections',
    toolLabel: 'Patient Collections Solutions',
  },
  {
    term: 'EFT (Electronic Funds Transfer)',
    acronym: 'EFT',
    category: 'tech',
    categoryLabel: 'Technology & EDI',
    definition: 'The secure electronic direct deposit of claim reimbursement funds from insurance health plans straight into a healthcare provider\'s commercial bank account.',
    clinicalImpact: 'Eliminates paper check delays, mail theft hazards, and physical banking trips, reducing days in accounts receivable by 7–14 days.',
    example: 'A practice links CAQH ERA/EFT enrollment so Blue Cross Blue Shield settlements deposit directly overnight.',
    toolHref: '/services/payment-posting',
    toolLabel: 'Payment Posting Automation',
  },
  {
    term: '277CA (Claims Acknowledgment)',
    acronym: '277CA',
    category: 'tech',
    categoryLabel: 'Technology & EDI',
    definition: 'An automated EDI transaction generated by clearinghouses and health plans immediately after receiving an 837 claim batch, confirming claim acceptance or rejection.',
    clinicalImpact: 'Reviewing 277CA reports daily prevents "silent rejections" where claims sit unadjudicated for months without ever entering the payer\'s processing queue.',
    example: 'A 277CA report flags a claim rejected at the gateway due to a missing patient middle initial in subscriber loop 2010BA.',
    toolHref: '/portal',
    toolLabel: 'Simulate Live 277CA Logs in Portal',
  },
  {
    term: 'Buy-and-Bill',
    category: 'claims',
    categoryLabel: 'Billing & Claims',
    definition: 'A healthcare revenue model where clinical practices purchase specialty medications, injectables, or implants up front, store them, administer them to patients, and bill the insurer.',
    clinicalImpact: 'Carries high capital risk. If a prior authorization is missing or an NDC code is miscalculated, the clinic bears the entire financial loss of high-cost medications.',
    example: 'A retina clinic buys $100,000 of anti-VEGF eye medication monthly, billing commercial payers using HCPCS J-codes upon patient administration.',
    toolHref: '/services/pharmacy-billing',
    toolLabel: 'Specialty Buy-and-Bill Services',
  },
  {
    term: 'Split/Shared Visit',
    category: 'coding',
    categoryLabel: 'Coding & Modifiers',
    definition: 'An Evaluation and Management (E/M) service performed jointly by a physician and an advanced practice provider (NP or PA) in a facility or hospital setting.',
    clinicalImpact: 'Under CMS regulations, the service must be billed under the clinician who performed the substantive portion (more than 50% of time or MDM) of the encounter.',
    example: 'A nurse practitioner and hospitalist round together on an inpatient; because the physician spent 35 of 50 total minutes, the claim is billed under the physician.',
    toolHref: '/medical-billing/internal-medicine',
    toolLabel: 'Hospital & E/M Billing Guide',
  },
  {
    term: 'Incident-To Billing',
    category: 'coding',
    categoryLabel: 'Coding & Modifiers',
    definition: 'A Medicare billing rule allowing services provided by non-physician providers (NPs/PAs) in an outpatient office to be billed under the supervising physician\'s NPI at 100% of the fee schedule.',
    clinicalImpact: 'Requires direct physician supervision on the premises during the visit. Failure to meet strict incident-to criteria leads to 15% reimbursement recoupment audits.',
    example: 'A physician is in the clinic office suite while their nurse practitioner follows up on an established diabetic patient, billing 100% allowable under the physician.',
    toolHref: '/services/compliance-auditing',
    toolLabel: 'Compliance & Audit Services',
  },
];
