// Generated by scripts/generate-routes.mjs. Edit route pages, not this file.
export const ROUTES = [
  {
    "path": "/",
    "indexable": true
  },
  {
    "path": "/about",
    "indexable": true
  },
  {
    "path": "/blog",
    "indexable": true
  },
  {
    "path": "/blog/editorial-policy",
    "indexable": true
  },
  {
    "path": "/careers",
    "indexable": true
  },
  {
    "path": "/case-studies",
    "indexable": true
  },
  {
    "path": "/compare",
    "indexable": true
  },
  {
    "path": "/compare/how-to-choose-a-medical-billing-company",
    "indexable": true
  },
  {
    "path": "/compare/outsourced-vs-in-house-medical-billing",
    "indexable": true
  },
  {
    "path": "/compliance",
    "indexable": true
  },
  {
    "path": "/compliance/baa",
    "indexable": true
  },
  {
    "path": "/compliance/hipaa",
    "indexable": true
  },
  {
    "path": "/compliance/privacy-policy",
    "indexable": true
  },
  {
    "path": "/compliance/security",
    "indexable": true
  },
  {
    "path": "/compliance/terms-of-service",
    "indexable": true
  },
  {
    "path": "/contact",
    "indexable": true
  },
  {
    "path": "/decks",
    "indexable": true
  },
  {
    "path": "/faq",
    "indexable": true
  },
  {
    "path": "/for-billing-companies",
    "indexable": true
  },
  {
    "path": "/free-assessment",
    "indexable": true
  },
  {
    "path": "/gap-analysis",
    "indexable": false
  },
  {
    "path": "/glossary",
    "indexable": true
  },
  {
    "path": "/integrations",
    "indexable": true
  },
  {
    "path": "/lp/asc-surgical-billing",
    "indexable": false
  },
  {
    "path": "/lp/behavioral-health-billing",
    "indexable": false
  },
  {
    "path": "/lp/denial-recovery-pilot",
    "indexable": false
  },
  {
    "path": "/lp/enterprise-rcm",
    "indexable": false
  },
  {
    "path": "/lp/fqhc-rhc-billing",
    "indexable": false
  },
  {
    "path": "/lp/home-health-hospice-billing",
    "indexable": false
  },
  {
    "path": "/lp/medicare-advantage-rcm",
    "indexable": false
  },
  {
    "path": "/lp/solo-practice-rcm",
    "indexable": false
  },
  {
    "path": "/lp/switch-medical-billing",
    "indexable": false
  },
  {
    "path": "/medical-billing",
    "indexable": true
  },
  {
    "path": "/payer-services",
    "indexable": true
  },
  {
    "path": "/payers",
    "indexable": true
  },
  {
    "path": "/payers/directory",
    "indexable": true
  },
  {
    "path": "/portal",
    "indexable": false
  },
  {
    "path": "/pricing",
    "indexable": true
  },
  {
    "path": "/process",
    "indexable": true
  },
  {
    "path": "/schedule",
    "indexable": true
  },
  {
    "path": "/services",
    "indexable": true
  },
  {
    "path": "/services/ar-followup",
    "indexable": true
  },
  {
    "path": "/services/cardiology-billing",
    "indexable": true
  },
  {
    "path": "/services/claims-billing",
    "indexable": true
  },
  {
    "path": "/services/compliance-auditing",
    "indexable": true
  },
  {
    "path": "/services/credentialing",
    "indexable": true
  },
  {
    "path": "/services/denial-management",
    "indexable": true
  },
  {
    "path": "/services/dental-billing",
    "indexable": true
  },
  {
    "path": "/services/dermatology-billing",
    "indexable": true
  },
  {
    "path": "/services/eligibility-verification",
    "indexable": true
  },
  {
    "path": "/services/family-medicine-billing",
    "indexable": true
  },
  {
    "path": "/services/medical-coding",
    "indexable": true
  },
  {
    "path": "/services/orthopedic-billing",
    "indexable": true
  },
  {
    "path": "/services/patient-collections",
    "indexable": true
  },
  {
    "path": "/services/payment-posting",
    "indexable": true
  },
  {
    "path": "/services/pharmacy-billing",
    "indexable": true
  },
  {
    "path": "/services/prior-authorization",
    "indexable": true
  },
  {
    "path": "/services/psychiatry-billing",
    "indexable": true
  },
  {
    "path": "/services/reporting-analytics",
    "indexable": true
  },
  {
    "path": "/services/telehealth-billing",
    "indexable": true
  },
  {
    "path": "/services/workers-compensation-billing",
    "indexable": true
  },
  {
    "path": "/specialties",
    "indexable": true
  },
  {
    "path": "/state-of-denials",
    "indexable": true
  },
  {
    "path": "/tools",
    "indexable": true
  },
  {
    "path": "/tools/achd-reoperation-scrubber",
    "indexable": true
  },
  {
    "path": "/tools/adult-retroperitoneal-sarcoma-scrubber",
    "indexable": true
  },
  {
    "path": "/tools/adult-spine-deformity-llif-scrubber",
    "indexable": true
  },
  {
    "path": "/tools/ambulance-fee-calculator",
    "indexable": true
  },
  {
    "path": "/tools/anesthesia-calculator",
    "indexable": true
  },
  {
    "path": "/tools/anesthesia-concurrency-auditor",
    "indexable": true
  },
  {
    "path": "/tools/appeal-letter-generator",
    "indexable": true
  },
  {
    "path": "/tools/ar-cost-calculator",
    "indexable": true
  },
  {
    "path": "/tools/cardiac-ep-scrubber",
    "indexable": true
  },
  {
    "path": "/tools/cardiothoracic-cannulation-scrubber",
    "indexable": true
  },
  {
    "path": "/tools/clean-claim-scorecard",
    "indexable": true
  },
  {
    "path": "/tools/clinical-trial-billing",
    "indexable": true
  },
  {
    "path": "/tools/colorectal-exenteration-scrubber",
    "indexable": true
  },
  {
    "path": "/tools/complex-robotic-hernia-tar-scrubber",
    "indexable": true
  },
  {
    "path": "/tools/credentialing-timeline-estimator",
    "indexable": true
  },
  {
    "path": "/tools/critical-care-scrubber",
    "indexable": true
  },
  {
    "path": "/tools/ctp-skin-substitute-calculator",
    "indexable": true
  },
  {
    "path": "/tools/denial-code-lookup",
    "indexable": true
  },
  {
    "path": "/tools/denial-cost-calculator",
    "indexable": true
  },
  {
    "path": "/tools/denial-overturn-predictor",
    "indexable": true
  },
  {
    "path": "/tools/dialysis-mcp-calculator",
    "indexable": true
  },
  {
    "path": "/tools/diep-flap-reconstruction-scrubber",
    "indexable": true
  },
  {
    "path": "/tools/dmepos-validator",
    "indexable": true
  },
  {
    "path": "/tools/edi-270-271-validator",
    "indexable": true
  },
  {
    "path": "/tools/edi-837-scrubber",
    "indexable": true
  },
  {
    "path": "/tools/eligibility-checklist",
    "indexable": true
  },
  {
    "path": "/tools/endoscopic-pituitary-odontoid-scrubber",
    "indexable": true
  },
  {
    "path": "/tools/era-835-decoder",
    "indexable": true
  },
  {
    "path": "/tools/fee-schedule-benchmarker",
    "indexable": true
  },
  {
    "path": "/tools/fqhc-pps-scrubber",
    "indexable": true
  },
  {
    "path": "/tools/global-period-scrubber",
    "indexable": true
  },
  {
    "path": "/tools/good-faith-estimate-generator",
    "indexable": true
  },
  {
    "path": "/tools/hcc-raf-calculator",
    "indexable": true
  },
  {
    "path": "/tools/head-and-neck-free-flap-scrubber",
    "indexable": true
  },
  {
    "path": "/tools/hepatobiliary-resection-scrubber",
    "indexable": true
  },
  {
    "path": "/tools/hipec-scrubber",
    "indexable": true
  },
  {
    "path": "/tools/lvad-cardiac-scrubber",
    "indexable": true
  },
  {
    "path": "/tools/mips-score-forecaster",
    "indexable": true
  },
  {
    "path": "/tools/modifier-compliance-engine",
    "indexable": true
  },
  {
    "path": "/tools/moldx-zcode-scrubber",
    "indexable": true
  },
  {
    "path": "/tools/msp-determination-engine",
    "indexable": true
  },
  {
    "path": "/tools/ncci-claim-scrubber",
    "indexable": true
  },
  {
    "path": "/tools/nicu-critical-care-scrubber",
    "indexable": true
  },
  {
    "path": "/tools/orthopedic-oncology-limb-salvage-scrubber",
    "indexable": true
  },
  {
    "path": "/tools/pad-revascularization-scrubber",
    "indexable": true
  },
  {
    "path": "/tools/panfacial-trauma-reconstruction-scrubber",
    "indexable": true
  },
  {
    "path": "/tools/patient-liability-estimator",
    "indexable": true
  },
  {
    "path": "/tools/payer-dispute-directory",
    "indexable": true
  },
  {
    "path": "/tools/payer-provider-manuals",
    "indexable": true
  },
  {
    "path": "/tools/pediatric-airway-scrubber",
    "indexable": true
  },
  {
    "path": "/tools/pediatric-biochemical-genetics-scrubber",
    "indexable": true
  },
  {
    "path": "/tools/pediatric-brain-tumor-scrubber",
    "indexable": true
  },
  {
    "path": "/tools/pediatric-cdh-ecmo-scrubber",
    "indexable": true
  },
  {
    "path": "/tools/pediatric-cell-therapy-scrubber",
    "indexable": true
  },
  {
    "path": "/tools/pediatric-craniofacial-scrubber",
    "indexable": true
  },
  {
    "path": "/tools/pediatric-craniosynostosis-scrubber",
    "indexable": true
  },
  {
    "path": "/tools/pediatric-dbs-neuromodulation-scrubber",
    "indexable": true
  },
  {
    "path": "/tools/pediatric-eos-scrubber",
    "indexable": true
  },
  {
    "path": "/tools/pediatric-epilepsy-scrubber",
    "indexable": true
  },
  {
    "path": "/tools/pediatric-facial-reanimation-scrubber",
    "indexable": true
  },
  {
    "path": "/tools/pediatric-hirschsprung-pull-through-scrubber",
    "indexable": true
  },
  {
    "path": "/tools/pediatric-mibg-radiopharmaceutical-scrubber",
    "indexable": true
  },
  {
    "path": "/tools/pediatric-pulmonary-estimator",
    "indexable": true
  },
  {
    "path": "/tools/pediatric-sct-coccygectomy-scrubber",
    "indexable": true
  },
  {
    "path": "/tools/pediatric-single-ventricle-norwood-scrubber",
    "indexable": true
  },
  {
    "path": "/tools/pediatric-tef-ea-scrubber",
    "indexable": true
  },
  {
    "path": "/tools/pediatric-tpiat-islet-transplant-scrubber",
    "indexable": true
  },
  {
    "path": "/tools/pediatric-transplant-scrubber",
    "indexable": true
  },
  {
    "path": "/tools/pediatric-vascular-malformations-scrubber",
    "indexable": true
  },
  {
    "path": "/tools/platform-telemetry",
    "indexable": false
  },
  {
    "path": "/tools/practice-benchmark-scorecard",
    "indexable": true
  },
  {
    "path": "/tools/practice-proposal-wizard",
    "indexable": true
  },
  {
    "path": "/tools/prior-auth-matrix",
    "indexable": true
  },
  {
    "path": "/tools/prompt-pay-statutes",
    "indexable": true
  },
  {
    "path": "/tools/rad-onc-scrubber",
    "indexable": true
  },
  {
    "path": "/tools/reconstructive-prior-auth-scrubber",
    "indexable": true
  },
  {
    "path": "/tools/retina-injection-scrubber",
    "indexable": true
  },
  {
    "path": "/tools/robotic-urologic-oncology-scrubber",
    "indexable": true
  },
  {
    "path": "/tools/rvu-calculator",
    "indexable": true
  },
  {
    "path": "/tools/scoliosis-deformity-scrubber",
    "indexable": true
  },
  {
    "path": "/tools/skull-base-bypass-aneurysm-scrubber",
    "indexable": true
  },
  {
    "path": "/tools/skull-base-scrubber",
    "indexable": true
  },
  {
    "path": "/tools/spine-arthrodesis-scrubber",
    "indexable": true
  },
  {
    "path": "/tools/taaa-fevar-scrubber",
    "indexable": true
  },
  {
    "path": "/tools/timely-filing-calculator",
    "indexable": true
  },
  {
    "path": "/tools/timely-filing-matrix",
    "indexable": true
  },
  {
    "path": "/tools/trauma-damage-control-scrubber",
    "indexable": true
  },
  {
    "path": "/tools/underpayment-analyzer",
    "indexable": true
  },
  {
    "path": "/tools/urogynecology-scrubber",
    "indexable": true
  },
  {
    "path": "/tools/vcr-spine-scrubber",
    "indexable": true
  },
  {
    "path": "/tools/whipple-resection-scrubber",
    "indexable": true
  }
] as const;
