import { test, expect } from './fixtures';
import { CONTACT_EMAIL } from '../../src/lib/business';
test('pilot modal validates three required fields, acknowledges receipt and closes by keyboard', async ({ page }) => {
  await page.goto('/');
  const trigger = page.getByRole('button', { name: 'Start the Free 50-Claim Pilot', exact: true });
  await trigger.click();
  const modal = page.getByRole('dialog');
  await expect(modal).toBeVisible();
  await expect(modal.getByText(/after the BAA, complete intake/)).toBeVisible();
  expect(await modal.locator('input[required]').count()).toBe(3);
  await modal.getByRole('button', { name: 'Request Free 50-Claim Pilot', exact: true }).click();
  await expect(modal.getByRole('heading', { name: 'Your request has been received' })).toHaveCount(0);
  await modal.getByLabel('Your name *', { exact: true }).fill('Kiran Kumar Pedapudi');
  await modal.getByLabel('Practice / organization *', { exact: true }).fill('Aethera Healthcare Solutions');
  await modal.getByLabel('Work email *', { exact: true }).fill(CONTACT_EMAIL);
  await modal.getByRole('button', { name: 'Request Free 50-Claim Pilot', exact: true }).click();
  await expect(modal.getByRole('heading', { name: 'Your request has been received' })).toBeVisible();
  await expect(modal.getByRole('link', { name: 'Schedule a meeting with Kiran' })).toBeVisible();
  await page.keyboard.press('Escape');
  await expect(modal).toHaveCount(0);
  await expect(trigger).toBeFocused();
});
