import Navbar from '@/components/layout/Navbar';
import Footer from '@/components/layout/Footer';
import RcmHeroBand from '@/components/ui/RcmHeroBand';
import OfferInquiry from '@/components/ui/OfferInquiry';
import { marketingMetadata } from '@/lib/marketing';
import { OFFERS } from '@/lib/siteConfig';
export const metadata = { ...marketingMetadata('/lp/denial-recovery-sprint', 'Free 48-Hour Denial Recovery Sprint', 'Request a free review of 5–10 denied claims. Findings in 48 hours after the BAA and complete EOBs and encounter notes. No EHR installation or long-term commitment.'), robots: { index: false, follow: true } };
export default function SprintPage() {
  return <><Navbar /><RcmHeroBand eyebrow="5–10 Denied Claims · No Obligation" title="Get a clear next step for your denied claims." subtitle={`The ${OFFERS.sprint.name} reviews denial evidence and prepares a recovery dossier. Findings in ${OFFERS.sprint.duration} ${OFFERS.sprint.start}.`} primary={{ href: '#sprint-request', label: 'Request the Free Sprint' }} secondary={{ href: '/schedule/', label: 'Discuss the sprint with Kiran' }} chips={['BAA before records', 'No EHR installation', 'Human review']} /><main className="mx-auto max-w-5xl px-5 py-12"><div className="grid gap-8 lg:grid-cols-2"><section className="space-y-5"><h2 className="text-2xl font-bold text-navy">What you receive</h2><ul className="list-disc space-y-3 pl-5 text-slate-700"><li>A review of denial reasons against the supplied EOBs and encounter documentation.</li><li>A claim-by-claim recovery dossier with the next review steps and relevant payer or CMS references.</li><li>Draft appeal letters where supported by the evidence, for human approval before submission.</li></ul><p className="text-sm text-slate-600">Your practice keeps recovered funds. Payer payment and appeal decisions are separate from the 48-hour findings timeline; recovery is not guaranteed.</p><h2 className="text-xl font-bold text-navy">Start with practice information</h2><p className="text-sm text-slate-700">We confirm scope, sign the BAA and arrange secure intake. Upload instructions are provided afterward; patient records do not belong in this form.</p></section><section id="sprint-request" className="scroll-mt-28 rounded-2xl border border-slate-200 bg-white p-6"><h2 className="mb-5 text-xl font-bold text-navy">Request the free sprint</h2><OfferInquiry offer="sprint" /></section></div></main><Footer /></>;
}
