import { readdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
async function walk(dir) {
  const entries = await readdir(dir, { withFileTypes: true });
  const files = await Promise.all(entries.map(e => e.isDirectory() ? walk(join(dir, e.name)) : [join(dir, e.name)]));
  return files.flat();
}
const pages = (await walk('src/app')).filter(p => p.endsWith('/page.tsx') && !p.includes('['));
const routes = pages.map(p => '/' + p.slice('src/app/'.length, -'/page.tsx'.length)).map(p => p === '/page.tsx' ? '/' : p);
// Root page does not have a directory separator before page.tsx after slicing.
if (!routes.includes('/')) routes.push('/');
const unique = [...new Set(routes)].filter(p => p !== '/page.tsx').sort();
const excluded = new Set(['/gap-analysis', '/portal', '/tools/platform-telemetry']);
const text = '// Generated by scripts/generate-routes.mjs. Edit route pages, not this file.\nexport const ROUTES = ' + JSON.stringify(unique.map(path => ({ path, indexable: !excluded.has(path) && !path.startsWith('/lp/') })), null, 2) + ' as const;\n';
const target = 'src/lib/routes.generated.ts';
if (process.argv.includes('--check')) {
  if (await readFile(target, 'utf8').catch(() => '') !== text) throw new Error('Route registry is stale. Run npm run routes:generate.');
} else await writeFile(target, text);
