import Link from 'next/link';
import Navbar from '@/components/layout/Navbar';
import Footer from '@/components/layout/Footer';
import CookiePreferencesButton from '@/components/ui/CookiePreferencesButton';
export const metadata = { title: 'Website privacy policy', description: 'Website contact data, local report processing, optional analytics and privacy choices.', alternates: { canonical: '/compliance/privacy-policy/' } };
export default function PrivacyPolicy() {
  return <><Navbar /><main className="max-w-3xl mx-auto px-4 py-16 space-y-6"><h1 className="text-4xl font-bold">Website privacy policy</h1><p className="text-muted">Updated September 7, 2026</p>
    <section className="space-y-3"><h2 className="text-2xl font-bold">Contact requests</h2><p>When you submit a form, we collect the contact and practice details you provide so our team can respond. Requests are sent to our website’s server endpoint, stored for delivery, and forwarded to our CRM. Please do not include patient identifiers or clinical records in public forms or chat.</p><p>The website does not save form contents to your browser’s localStorage. Opaque retry identifiers may be kept in sessionStorage for up to one hour to avoid duplicate submissions. Server delivery records are removed after 30 days following successful delivery by the maintenance job. CRM retention is managed separately by our team; pending requests remain available for follow-up.</p></section>
    <section className="space-y-3"><h2 className="text-2xl font-bold">Reports and assistant</h2><p>Files selected for the free assessment are parsed locally in your browser. The original file is not uploaded. If you submit an assessment, the form sends your contact details and aggregate totals to our team. Use de-identified files. Questions sent to the assistant may be processed by our assistant service and its model provider; do not share protected health information.</p></section>
    <section className="space-y-3"><h2 className="text-2xl font-bold">Optional analytics and advertising</h2><p>With your acceptance, configured services can measure visits, campaign attribution and advertising performance. They may include Google Analytics/Ads, Cloudflare Analytics, LinkedIn, Meta, RB2B, Apollo, Leadfeeder or Snitcher. Business visitor identification services may associate a visit with business contact information. Essential Only keeps these optional website integrations off.</p><p>Your preference is stored for up to 180 days. You can change it below. Withdrawing acceptance reloads the page to stop previously loaded tracking scripts; it does not recall data already sent.</p><CookiePreferencesButton /></section>
    <section className="space-y-3"><h2 className="text-2xl font-bold">Questions and service agreements</h2><p>Contact us to request a correction, discuss retention, or ask about your data. This policy describes the public website. Handling patient records for contracted billing work requires separate agreements and an approved secure transfer process.</p><Link href="/contact/" className="underline font-semibold">Contact our team</Link></section>
  </main><Footer /></>;
}
