'use client';
import { DEFAULT_OPACITY, type CutPlane, type ModelLayer } from '@/data/anatomyStudy';
import type { StudyView } from './AnatomyViewer';

export const DEFAULT_STUDY_VIEW: StudyView = { opacity: DEFAULT_OPACITY, hidden: [], context: false, plane: 'off', slice: 50, labels: true };
const groups: { id: ModelLayer; name: string }[] = [{ id: 'skeleton', name: 'Bones and discs' }, { id: 'organs', name: 'Organs' }, { id: 'nervous', name: 'Brain' }, { id: 'surface', name: 'Body surface' }];

export default function StudyControls({ value, onChange }: { value: StudyView; onChange: (value: StudyView) => void }) {
  return <details className="mt-4 rounded-xl border border-slate-200 bg-white p-5"><summary className="cursor-pointer font-semibold text-teal-900">Layers, transparency & cutaway</summary><div className="mt-5 space-y-5">
    <p className="text-sm leading-relaxed text-slate-600">These controls refine the region and layer selected in the side panel. Context shows neighboring structures faintly around a selected structure.</p>
    <div className="flex flex-wrap gap-x-6 gap-y-3 text-sm"><label className="flex items-center gap-2"><input type="checkbox" checked={value.context} onChange={e => onChange({ ...value, context: e.target.checked })} className="accent-teal-800" />Show surrounding anatomy</label><label className="flex items-center gap-2"><input type="checkbox" checked={value.labels} onChange={e => onChange({ ...value, labels: e.target.checked })} className="accent-teal-800" />Show view labels</label></div>
    <fieldset><legend className="font-semibold text-sm text-slate-900">Visibility and opacity</legend><div className="mt-3 grid gap-4 sm:grid-cols-2">{groups.map(group => <div key={group.id} className="rounded-lg bg-slate-50 p-3"><label className="flex items-center gap-2 text-sm font-medium"><input type="checkbox" checked={!value.hidden.includes(group.id)} onChange={e => onChange({ ...value, hidden: e.target.checked ? value.hidden.filter(id => id !== group.id) : [...value.hidden, group.id] })} className="accent-teal-800" />Show {group.name.toLowerCase()}</label><label className="mt-3 block text-xs text-slate-600">{group.name} opacity: {Math.round(value.opacity[group.id] * 100)}%<input aria-label={`${group.name} opacity`} className="mt-2 block w-full accent-teal-800" type="range" min="10" max="100" step="1" value={Math.round(value.opacity[group.id] * 100)} disabled={value.hidden.includes(group.id)} onChange={e => onChange({ ...value, opacity: { ...value.opacity, [group.id]: Number(e.target.value) / 100 } })} /></label></div>)}</div></fieldset>
    <div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">Surface cutaway<select aria-label="Surface cutaway" className="mt-2 w-full rounded-lg border border-slate-300 bg-white p-3 text-sm" value={value.plane} onChange={e => onChange({ ...value, plane: e.target.value as CutPlane })}><option value="off">Off — intact surfaces</option><option value="sagittal">Sagittal — left/right</option><option value="coronal">Coronal — front/back</option><option value="transverse">Transverse — upper/lower</option></select></label><label className="text-sm font-semibold">Cutaway position: {value.slice}%<input aria-label="Cutaway position" className="mt-5 block w-full accent-teal-800" type="range" min="0" max="100" value={value.slice} disabled={value.plane === 'off'} onChange={e => onChange({ ...value, slice: Number(e.target.value) })} /></label></div>
    <button className="rounded-lg border border-slate-300 px-4 py-2 text-sm font-semibold text-teal-800" onClick={() => onChange(DEFAULT_STUDY_VIEW)}>Reset study view</button>
  </div></details>;
}
