import type { Metadata } from 'next';
import Navbar from '@/components/layout/Navbar';
import Footer from '@/components/layout/Footer';
import { CMS_DOCUMENTS, cmsReaderUrl } from '@/data/cmsDocuments';
import { canonicalUrl } from '@/lib/siteConfig';

export const metadata: Metadata = { title: 'CMS Reference Access | Aethera Healthcare', description: 'Access selected public CMS documents through Aethera’s Cloudflare document reader, with original source links.', alternates: { canonical: canonicalUrl('/cms-references') } };
export default function CmsReferencesPage() {
  return <><Navbar /><main id="main-content" className="mx-auto max-w-5xl px-5 py-16 text-slate-800"><p className="text-sm font-semibold uppercase tracking-widest text-teal-800">Learning resources</p><h1 className="mt-3 text-4xl font-bold text-slate-950">CMS reference access</h1><p className="mt-5 max-w-3xl leading-relaxed">If a direct CMS download is denied on your network, try retrieving the document through our Cloudflare reader. Each request fetches the selected public PDF from CMS; documents are not edited or permanently archived here.</p><p className="mt-4 max-w-3xl text-sm leading-relaxed text-slate-600">This is an alternative access route, not an official CMS service or a guarantee of availability. It supports the listed PDFs only, not general CMS browsing, logins or claim submission. CMS may also deny the Cloudflare request. Source editions and effective dates still govern how the content is used.</p><div className="mt-8 grid gap-5 sm:grid-cols-2">{CMS_DOCUMENTS.map(document => <article key={document.id} className="rounded-xl border border-slate-200 bg-white p-6"><h2 className="text-lg font-semibold text-slate-950">{document.title}</h2><div className="mt-5 flex flex-wrap gap-4 text-sm font-semibold"><a className="rounded-lg bg-teal-800 px-4 py-3 text-white" href={cmsReaderUrl(document.id)} target="_blank" rel="noopener noreferrer">Try Cloudflare reader<span className="sr-only"> for {document.title} (opens a new tab)</span></a><a className="self-center text-teal-800 underline" href={document.official}>Official CMS source<span className="sr-only"> for {document.title}</span></a></div></article>)}</div><p className="mt-8 text-sm leading-relaxed text-slate-600">For anatomy-atlas citations, use the 2026 combined NCCI manual and its PDF page number. A standalone chapter’s PDF numbering differs. Copyright and third-party notices remain in the original documents.</p><a className="mt-6 inline-block font-semibold text-teal-800 underline" href="/anatomy-atlas/">Return to the anatomy atlas</a></main><Footer /></>;
}
